# AUTO-GÉNÉRÉ par tools/generate_bilan_constants.py
# Source : plugins/clickhouse/bilan_reference.py (référentiel Python validé)

BILAN_LABELS = {
    'AD': 'Immobilisations incorporelles',
    'AD1': 'Amortissement des immobilisations incorporelles',
    'AD2': 'Provisions pour dépréciation des immobilisations incorporelles',
    'AE': 'Frais développement',
    'AE1': 'Amortissement des frais de recherche et de développement',
    'AF': 'Brevets licences logiciels',
    'AF1': 'Amortissement des brevets, licences, concessions et droits similaires, logiciels',
    'AF2': 'Provisions pour dépréciation des brevets, licences, concessions et droits similaires',
    'AG': 'Fonds commercial',
    'AG1': 'Amortissement du fonds commercial et droit au bail',
    'AG2': 'Provisions pour dépréciation fonds commercial et droit au bail',
    'AH': 'Autres incorporelles',
    'AH1': 'Amortissement des biens incorporels',
    'AH2': 'Provisions pour dépréciation autres droits et valeurs',
    'AI': 'Immobilisations corporelles',
    'AI1': 'Amortissement des immobilisations corporelles',
    'AI2': 'Provisions pour dépréciation des immobilisations corporelles',
    'AJ': 'Terrains',
    'AJ1': 'Amortissement des terrains',
    'AJ2': 'Provisions pour dépréciation des terrains',
    'AK': 'Bâtiments',
    'AKL1': 'Amortissements des bâtiments, installations techniques et agencements',
    'AKL2': 'Provisions pour dépréciation des bâtiments, installations techniques et agencements',
    'AL': 'Installations',
    'AM': 'Matériel',
    'AM1': 'Amortissement du matériel',
    'AMN': 'Provisions pour dépréciation de matériel',
    'AN': 'Transport',
    'AN1': 'Amortissement du matériel de transport',
    'AP': 'Avances immobilisations',
    'AP2': 'Provisions pour dépréciation des avances et acomptes sur immobilisations',
    'AQ': 'Immobilisations financières',
    'AR': 'Titres participation',
    'AR2': 'Provisions pour dépréciation des titres de participation',
    'AS': 'Autres financières',
    'AS2': 'Provisions pour dépréciation des autres immobilisations financières',
    'AZ': 'Total actif immobilisé',
    'BA': 'Actif Circulant HAO',
    'BB': 'Stocks et Encours',
    'BG': 'Créances et Emplois Assimilés',
    'BH': 'Avances fournisseurs',
    'BI': 'Clients',
    'BJ': 'Autres créances',
    'BK': 'Total Actif Circulant',
    'BQ': 'Titres placement',
    'BQ2': 'Dépréciation des titres de placement',
    'BR': 'Valeurs à encaisser',
    'BR2': 'Dépréciation des valeurs à encaisser',
    'BS': 'Banques, chèques postaux, caisse et assimilés',
    'BS2': 'Dépréciation des comptes banques, établissements financiers et assimilés',
    'BSA': 'Caisse',
    'BSB': 'Banques',
    'BSC': 'Autres trésoreries',
    'BT': 'Total Trésorerie Actif',
    'BU': 'Écart conversion actif',
    'BZ': 'Total actif',
    'CA': 'Capital',
    'CB': 'Capital non appelé',
    'CCA': "Charges constatées d'avance",
    'CD': 'Primes liées au capital',
    'CE': 'Écart réévaluation',
    'CF': 'Réserves indisponibles',
    'CG': 'Réserves libres',
    'CH': 'Report à nouveau',
    'CJ': 'Résultat',
    'CL': 'Subventions',
    'CM': 'Provisions réglementées',
    'CP': 'Total capitaux propres',
    'DA': 'Emprunts',
    'DB': 'Crédit bail',
    'DC': 'Provisions LT',
    'DD': 'Total Dettes Financières et Ressources assimilées',
    'DF': 'Total ressources stables',
    'DH': 'Dettes circulantes HAO',
    'DI': 'Clients avances reçues',
    'DJ': 'Fournisseurs',
    'DK': 'Dettes fiscales et sociales',
    'DK1': 'Dettes Personnel',
    'DK2': 'Dettes sociales',
    'DK3': 'Dettes fiscales',
    'DM': 'Autres dettes',
    'DN': 'Provisions pour risques et charges à court terme',
    'DP': 'Total Passif Circulant',
    'DQ': "Banques, crédits d'escompte",
    'DR': 'Banques, établissements financiers et crédits de trésorerie',
    'DT': 'Trésorerie passif',
    'DV': 'Écart conversion passif',
    'DZ': 'Total passif',
    'PCA': "Produits constatés d'avance",
    'RPCF': 'Risques provisionnés à caractère financier',
    'RPCP': 'Répartition périodique des charges et produits',
}

BILAN_COMPOSITION = {
    'AD': ['AE', 'AF', 'AG', 'AH'],
    'AD1': ['AE1', 'AF1', 'AG1', 'AH1'],
    'AD2': ['AF2', 'AG2', 'AH2'],
    'AI': ['AJ', 'AK', 'AL', 'AM', 'AN', 'AP'],
    'AI1': ['AJ1', 'AKL1', 'AM1', 'AN1'],
    'AI2': ['AJ2', 'AKL2', 'AMN', 'AP2'],
    'AQ': ['AR', 'AS'],
    'AZ': ['AD', 'AI', 'AQ'],
    'BG': ['BH', 'BI', 'BJ'],
    'BK': ['BA', 'BB', 'BG'],
    'BS': ['BSA', 'BSB', 'BSC'],
    'BT': ['BQ', 'BR', 'BS'],
    'BZ': ['AZ', 'BK', 'BT', 'BU'],
    'CP': ['CA', 'CB', 'CD', 'CE', 'CF', 'CG', 'CH', 'CJ', 'CL', 'CM'],
    'DD': ['DA', 'DB', 'DC'],
    'DF': ['CP', 'DD'],
    'DK': ['DK1', 'DK2', 'DK3'],
    'DP': ['DH', 'DI', 'DJ', 'DK', 'DM', 'DN'],
    'DT': ['DQ', 'DR'],
    'DZ': ['CP', 'DF', 'DP', 'DT', 'DV'],
}

BILAN_SUBDIVISIONS = {
    'BS': {
        'BSA': {'libelle': 'Caisse', 'racine': '57', 'nb_racine': 2},
        'BSB': {'libelle': 'Banques', 'racine': '52', 'nb_racine': 2},
        'BSC': {'libelle': 'Autres trésoreries', 'racine': '53', 'nb_racine': 2},
    },
    'DK': {
        'DK1': {'libelle': 'Dettes Personnel', 'racine': '42', 'nb_racine': 2},
        'DK2': {'libelle': 'Dettes sociales', 'racine': '43', 'nb_racine': 2},
        'DK3': {'libelle': 'Dettes fiscales', 'racine': '44', 'nb_racine': 2},
    },
}

BILAN_MAPPING_DATA = [
    ('211', 'AE', 3, '', []),
    ('2191', 'AE', 4, '', []),
    ('2811', 'AE1', 4, '', []),
    ('212', 'AF', 3, '', []),
    ('213', 'AF', 3, '', []),
    ('214', 'AF', 3, '', []),
    ('2193', 'AF', 4, '', []),
    ('2812', 'AF1', 4, '', []),
    ('2813', 'AF1', 4, '', []),
    ('2814', 'AF1', 4, '', []),
    ('2912', 'AF2', 4, '', []),
    ('2913', 'AF2', 4, '', []),
    ('2914', 'AF2', 4, '', []),
    ('215', 'AG', 3, '', []),
    ('216', 'AG', 3, '', []),
    ('2815', 'AG1', 4, '', []),
    ('2816', 'AG1', 4, '', []),
    ('2915', 'AG2', 4, '', []),
    ('2916', 'AG2', 4, '', []),
    ('217', 'AH', 3, '', []),
    ('218', 'AH', 3, '', []),
    ('2198', 'AH', 4, '', []),
    ('2817', 'AH1', 4, '', []),
    ('2818', 'AH1', 4, '', []),
    ('2917', 'AH2', 4, '', []),
    ('2918', 'AH2', 4, '', []),
    ('2919', 'AH2', 4, '', []),
    ('22', 'AJ', 2, '', []),
    ('282', 'AJ1', 3, '', []),
    ('292', 'AJ2', 3, '', []),
    ('231', 'AK', 3, '', []),
    ('232', 'AK', 3, '', []),
    ('237', 'AK', 3, '', []),
    ('239', 'AK', 3, '', []),
    ('283', 'AKL1', 3, '', []),
    ('293', 'AKL2', 3, '', []),
    ('233', 'AL', 3, '', []),
    ('234', 'AL', 3, '', []),
    ('235', 'AL', 3, '', []),
    ('238', 'AL', 3, '', []),
    ('241', 'AM', 3, '', []),
    ('242', 'AM', 3, '', []),
    ('243', 'AM', 3, '', []),
    ('244', 'AM', 3, '', []),
    ('246', 'AM', 3, '', []),
    ('247', 'AM', 3, '', []),
    ('248', 'AM', 3, '', []),
    ('2491', 'AM', 4, '', []),
    ('2492', 'AM', 4, '', []),
    ('2493', 'AM', 4, '', []),
    ('2494', 'AM', 4, '', []),
    ('2496', 'AM', 4, '', []),
    ('2497', 'AM', 4, '', []),
    ('2498', 'AM', 4, '', []),
    ('284', 'AM1', 3, '', ['2845']),
    ('294', 'AMN', 3, '', []),
    ('245', 'AN', 3, '', []),
    ('2495', 'AN', 4, '', []),
    ('2845', 'AN1', 4, '', []),
    ('25', 'AP', 2, '', []),
    ('295', 'AP2', 3, '', []),
    ('26', 'AR', 2, '', []),
    ('296', 'AR2', 3, '', []),
    ('27', 'AS', 2, '', []),
    ('297', 'AS2', 3, '', []),
    ('485', 'BA', 3, '', []),
    ('486', 'BA', 3, '', []),
    ('488', 'BA', 3, '', []),
    ('31', 'BB', 2, '', []),
    ('32', 'BB', 2, '', []),
    ('33', 'BB', 2, '', []),
    ('34', 'BB', 2, '', []),
    ('35', 'BB', 2, '', []),
    ('36', 'BB', 2, '', []),
    ('37', 'BB', 2, '', []),
    ('38', 'BB', 2, '', []),
    ('39', 'BB', 2, '', []),
    ('409', 'BH', 3, '', []),
    ('41', 'BI', 2, '', ['419']),
    ('4711', 'BJ', 4, '', []),
    ('472', 'BJ', 3, '', []),
    ('475', 'BJ', 3, '', []),
    ('50', 'BQ', 2, '', []),
    ('590', 'BQ2', 3, '', []),
    ('51', 'BR', 2, '', []),
    ('591', 'BR2', 3, '', []),
    ('592', 'BS2', 3, '', []),
    ('593', 'BS2', 3, '', []),
    ('594', 'BS2', 3, '', []),
    ('57', 'BSA', 2, '', []),
    ('52', 'BSB', 2, '', []),
    ('53', 'BSC', 2, '', []),
    ('54', 'BSC', 2, '', []),
    ('478', 'BU', 3, '', []),
    ('10', 'CA', 2, '', ['105', '106', '109']),
    ('109', 'CB', 3, '', []),
    ('476', 'CCA', 3, '', []),
    ('105', 'CD', 3, '', []),
    ('106', 'CE', 3, '', []),
    ('111', 'CF', 3, '', []),
    ('112', 'CF', 3, '', []),
    ('113', 'CF', 3, '', []),
    ('118', 'CG', 3, '', []),
    ('12', 'CH', 2, '', []),
    ('13', 'CJ', 2, '', []),
    ('14', 'CL', 2, '', []),
    ('15', 'CM', 2, '', []),
    ('16', 'DA', 2, '', []),
    ('18', 'DA', 2, '', []),
    ('17', 'DB', 2, '', []),
    ('19', 'DC', 2, '', []),
    ('481', 'DH', 3, '', []),
    ('482', 'DH', 3, '', []),
    ('483', 'DH', 3, '', []),
    ('484', 'DH', 3, '', []),
    ('419', 'DI', 3, '', []),
    ('401', 'DJ', 3, '', []),
    ('402', 'DJ', 3, '', []),
    ('403', 'DJ', 3, '', []),
    ('404', 'DJ', 3, '', []),
    ('405', 'DJ', 3, '', []),
    ('406', 'DJ', 3, '', []),
    ('407', 'DJ', 3, '', []),
    ('408', 'DJ', 3, '', []),
    ('42', 'DK1', 2, '', []),
    ('43', 'DK2', 2, '', []),
    ('44', 'DK3', 2, '', []),
    ('45', 'DM', 2, '', []),
    ('46', 'DM', 2, '', []),
    ('4712', 'DM', 4, '', []),
    ('49', 'DN', 2, '', []),
    ('564', 'DQ', 3, '', []),
    ('565', 'DQ', 3, '', []),
    ('561', 'DR', 3, '', []),
    ('566', 'DR', 3, '', []),
    ('479', 'DV', 3, '', []),
    ('477', 'PCA', 3, '', []),
    ('599', 'RPCF', 3, '', []),
    ('474', 'RPCP', 3, '', []),
]
