# AUTO-GÉNÉRÉ par tools/generate_bilan_constants.py
# Source : plugins/clickhouse/bilan_reference.py (référentiel Python validé)

BILAN_LABELS = {
    'AD': 'Immobilisations incorporelles',
    'AE': 'Frais développement',
    'AF': 'Brevets licences logiciels',
    'AG': 'Fonds commercial',
    'AH': 'Autres incorporelles',
    'AI': 'Immobilisations corporelles',
    'AJ': 'Terrains',
    'AK': 'Bâtiments',
    'AL': 'Installations',
    'AM': 'Matériel',
    'AN': 'Transport',
    'AP': 'Avances immobilisations',
    'AQ': 'Immobilisations financières',
    'AR': 'Titres participation',
    'AS': 'Autres financières',
    'AZ': 'Total actif immobilisé',
    'BA': 'Actif Circulant HAO',
    'BB': 'Stocks et Encours',
    'BG': 'Créances et Emplois Assimilés',
    'BH': 'Avances fournisseurs',
    'BI': 'Clients',
    'BJ': 'Autres créances',
    'BK': 'Total Actif Circulant',
    'BQ': 'Titres placement',
    'BR': 'Valeurs à encaisser',
    'BS': 'Banques et caisse',
    'BT': 'Total Trésorerie Actif',
    'BU': 'Écart conversion actif',
    'BZ': 'Total actif',
    'CA': 'Capital',
    'CB': 'Capital non appelé',
    'CD': 'Primes',
    'CE': 'Écart réévaluation',
    'CF': 'Réserves indisponibles',
    'CG': 'Réserves libres',
    'CH': 'Report à nouveau',
    'CJ': 'Résultat',
    'CL': 'Subventions',
    'CM': 'Provisions réglementées',
    'CP': 'Total capitaux propres',
    'DA': 'Emprunts',
    'DB': 'Crédit bail',
    'DC': 'Provisions LT',
    'DD': 'Total Dettes Financières et Ressources assimilées',
    'DF': 'Total ressources stables',
    'DH': 'Dettes circulantes HAO',
    'DI': 'Clients avances reçues',
    'DJ': 'Fournisseurs',
    'DK': 'Dettes fiscales et sociales',
    'DK1': 'Dettes Personnel',
    'DK2': 'Dettes sociales',
    'DK3': 'Dettes fiscales',
    'DM': 'Autres dettes',
    'DN': 'Provisions CT',
    'DP': 'Total Passif Circulant',
    'DQ': "Banques, crédits d'escompte",
    'DR': 'Concours bancaires',
    'DT': 'Trésorerie passif',
    'DV': 'Écart conversion passif',
    'DZ': 'Total passif',
}

BILAN_COMPOSITION = {
    'AD': ['AE', 'AF', 'AG', 'AH'],
    'AI': ['AJ', 'AK', 'AL', 'AM', 'AN', 'AP'],
    'AQ': ['AR', 'AS'],
    'AZ': ['AD', 'AI', 'AQ'],
    'BG': ['BH', 'BI', 'BJ'],
    'BK': ['BA', 'BB', 'BG'],
    'BT': ['BQ', 'BR', 'BS'],
    'BZ': ['AZ', 'BK', 'BT', 'BU'],
    'CP': ['CA', 'CB', 'CD', 'CE', 'CF', 'CG', 'CH', 'CJ', 'CL', 'CM'],
    'DD': ['DA', 'DB', 'DC'],
    'DF': ['CP', 'DD'],
    'DK': ['DK1', 'DK2', 'DK3'],
    'DP': ['DH', 'DI', 'DJ', 'DK', 'DM', 'DN'],
    'DT': ['DQ', 'DR'],
    'DZ': ['CP', 'DF', 'DP', 'DT', 'DV'],
}

BILAN_SUBDIVISIONS = {
    'DK': {
        'DK1': {'libelle': 'Dettes Personnel', 'racine': '42', 'nb_racine': 2},
        'DK2': {'libelle': 'Dettes sociales', 'racine': '43', 'nb_racine': 2},
        'DK3': {'libelle': 'Dettes fiscales', 'racine': '44', 'nb_racine': 2},
    },
}

BILAN_MAPPING_DATA = [
    ('201', 'AE', 3, '', []),
    ('204', 'AF', 3, '', []),
    ('206', 'AG', 3, '', []),
    ('208', 'AH', 3, '', []),
    ('211', 'AJ', 3, '', []),
    ('213', 'AK', 3, '', []),
    ('214', 'AL', 3, '', []),
    ('215', 'AM', 3, '', []),
    ('218', 'AN', 3, '', []),
    ('23', 'AP', 2, '', []),
    ('261', 'AR', 3, '', []),
    ('271', 'AS', 3, '', []),
    ('272', 'AS', 3, '', []),
    ('273', 'AS', 3, '', []),
    ('274', 'AS', 3, '', []),
    ('275', 'AS', 3, '', []),
    ('471', 'BA', 3, 'debit', []),
    ('478', 'BA', 3, 'debit', []),
    ('488', 'BA', 3, '', []),
    ('31', 'BB', 2, '', []),
    ('32', 'BB', 2, '', []),
    ('33', 'BB', 2, '', []),
    ('34', 'BB', 2, '', []),
    ('35', 'BB', 2, '', []),
    ('36', 'BB', 2, '', []),
    ('37', 'BB', 2, '', []),
    ('38', 'BB', 2, '', []),
    ('39', 'BB', 2, '', []),
    ('409', 'BH', 3, '', []),
    ('41', 'BI', 2, '', ['419']),
    ('42', 'BJ', 2, '', ['42', '43', '44', '471', '478', '488']),
    ('43', 'BJ', 2, '', ['42', '43', '44', '471', '478', '488']),
    ('44', 'BJ', 2, '', ['42', '43', '44', '471', '478', '488']),
    ('45', 'BJ', 2, '', ['42', '43', '44', '471', '478', '488']),
    ('46', 'BJ', 2, '', ['42', '43', '44', '471', '478', '488']),
    ('47', 'BJ', 2, '', ['42', '43', '44', '471', '478', '488']),
    ('48', 'BJ', 2, '', ['42', '43', '44', '471', '478', '488']),
    ('50', 'BQ', 2, '', []),
    ('512', 'BR', 3, '', []),
    ('52', 'BS', 2, 'debit', []),
    ('53', 'BS', 2, '', []),
    ('57', 'BS', 2, '', []),
    ('476', 'BU', 3, '', []),
    ('10', 'CA', 2, '', []),
    ('109', 'CB', 3, '', []),
    ('11', 'CD', 2, '', []),
    ('105', 'CE', 3, '', []),
    ('111', 'CF', 3, '', []),
    ('112', 'CG', 3, '', []),
    ('12', 'CH', 2, '', []),
    ('13', 'CJ', 2, '', []),
    ('14', 'CL', 2, '', []),
    ('15', 'CM', 2, '', []),
    ('16', 'DA', 2, '', ['167']),
    ('167', 'DB', 3, '', []),
    ('191', 'DC', 3, '', []),
    ('192', 'DC', 3, '', []),
    ('193', 'DC', 3, '', []),
    ('194', 'DC', 3, '', []),
    ('471', 'DH', 3, 'credit', []),
    ('478', 'DH', 3, 'credit', []),
    ('485', 'DH', 3, '', []),
    ('419', 'DI', 3, '', []),
    ('401', 'DJ', 3, '', []),
    ('402', 'DJ', 3, '', []),
    ('403', 'DJ', 3, '', []),
    ('404', 'DJ', 3, '', []),
    ('405', 'DJ', 3, '', []),
    ('406', 'DJ', 3, '', []),
    ('407', 'DJ', 3, '', []),
    ('408', 'DJ', 3, '', []),
    ('42', 'DK1', 2, '', []),
    ('43', 'DK2', 2, '', []),
    ('44', 'DK3', 2, '', []),
    ('45', 'DM', 2, '', ['471', '478', '485']),
    ('46', 'DM', 2, '', ['471', '478', '485']),
    ('47', 'DM', 2, '', ['471', '478', '485']),
    ('48', 'DM', 2, '', ['471', '478', '485']),
    ('195', 'DN', 3, '', []),
    ('196', 'DN', 3, '', []),
    ('197', 'DN', 3, '', []),
    ('198', 'DN', 3, '', []),
    ('199', 'DN', 3, '', []),
    ('52', 'DQ', 2, 'credit', []),
    ('519', 'DR', 3, '', []),
    ('477', 'DV', 3, '', []),
]
